# Generated by Django 3.2 on 2023-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('emp', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('expenses_monthly', models.IntegerField(default=0)),
                ('income_monthly', models.IntegerField(default=0)),
            ],
        ),
    ]
